---
  name: Python Quality Check and Formatting
  # Controls when the workflow will run
  on:
    push:
      branches:
        - master
        - main
    pull_request:
  # The sequence of runs in this workflow:
  jobs:
    lint:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        - run: lsb_release -a
        - run: uname -a
        - name: Check out Repository Code
          uses: actions/checkout@v3
          with:
            submodules: true # Fetch submodules
            fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
        - name: Initialize virtual environment
          run: |
            python3 -m venv venv
        - name: Install dependencies
          run: |
            source ./venv/bin/activate
            pip install poetry
            poetry install --no-root
        - name: Format code with black
          run: |
            source ./venv/bin/activate
            black src/ --line-length=120
        - name: Sort imports with isort
          run: |
            source ./venv/bin/activate
            isort src/ --profile black
        - name: Remove unused imports with autoflake
          run: |
            source ./venv/bin/activate
            autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive src/
        - name: Upgrade code syntax with pyupgrade
          run: |
            source ./venv/bin/activate
            find src/ -name '*.py' -exec pyupgrade --py39-plus --keep-runtime-typing {} \;
        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            author_name: ${{ github.actor }}
            author_email: ${{ github.actor }}@users.noreply.github.com
            message: "Code formatting and linting"
            add: "." # Add all files